// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  type NaiveUiComponents = typeof import('naive-ui')

  // 将 naive-ui 的所有类型继承, 兼容插件模板提示
  // eslint-disable-next-line @typescript-eslint/no-empty-interface
  export interface GlobalComponents extends NaiveUiComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
